USE `blog-project`;

CREATE TABLE IF NOT EXISTS `users`(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name TINYTEXT UNIQUE NOT NULL,
    email TINYTEXT UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);